Repository napzakmarket/Napzak-iOS, pull requests merged in 2025-07, with the labels that each got.

#135 [Feat] #131 - Loading View 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/LoadingView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/LoadingViewManager.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/ViewModel/GenreSelectModalViewModel.swift
  Napzak-iOS/Napzak-iOS/Global/Components/SpinnerLoadingView.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Animation/ios_loading.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Animation/spinner.json
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/ViewModel/ProductDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: 한열 🧄, Feat 💻

#141 [Style] #138 - 채팅 목록 뷰 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Literals/ColorLiteral.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Components/ChatItemView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatRoomModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/ViewModel/ChatViewModel.swift
Labels: 혜린 🎀, Style 🖼️

#145 [Feat] #143 - 채팅방 내부 모달 및 팝업 구현
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/ReportModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NZAlertView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/img_exit_modal.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/img_exit_modal.imageset/img_exit_modal.svg
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Components/ChatImageMessage.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawConfirmView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: Feat 💻

#148 [Feat] #144 - WebSocket 구현 및 채팅 관련 API 일부 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatService.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Request/ChatRoomCreateRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatDetailResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatRoomCreateResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatRoomEnterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Manager/ChatStompManager.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatDetailModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/ViewModel/ChatDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Feat 💻
