Repository napzakmarket/Napzak-iOS, pull requests merged in 2025-05, with the labels that each got.

#50 [Refactor/Network] #48 store API 추가 및 UI 수정
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/logo.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/logo.imageset/logo.svg
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Request/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Request/StoreModifyProfileRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreDetailDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreModifyProfileResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreProfileDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 어진 🧸, Refactor 🏗️, Network 📡

#53 [Network] #52 - ReportView API 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Report/DTO/Request/ReportRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Report/DTO/Response/ReportResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Report/ReportAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Report/ReportService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/Model/ReportModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/View/ReportView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/ViewModel/ReportViewModel.swift
Labels: 한열 🧄, Network 📡

#54 [Feat] #41 - 로그인 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/Napzak_iOSApp.swift
  Napzak-iOS/Napzak-iOS/Application/RootView.swift
  Napzak-iOS/Napzak-iOS/Global/Core/.gitkeep
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/AuthManager.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/Error/AuthError.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/KeychainManager.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/SocialLogin/Adapters/AppleLoginAdapter.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/SocialLogin/Adapters/KakaoLoginAdapter.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/SocialLogin/SocialLoginService.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/SocialLogin/SocialLoginType.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/TokenRefresher.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Onboarding/AuthNavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Onboarding/OnboardingManager.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Onboarding/OnboardingStep.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__apple.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__apple.imageset/button_login__apple.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__apple.imageset/button_login__apple@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__apple.imageset/button_login__apple@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__kakao.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__kakao.imageset/button_login__kakao.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__kakao.imageset/button_login__kakao@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Splash/button_login__kakao.imageset/button_login__kakao@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Napzak-iOS.entitlements
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthService.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Request/LoginRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/AuthResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/TokenResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/UserRole.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/TokenRefreshService.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseService.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseTargetType.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreService.swift
  Napzak-iOS/Napzak-iOS/Network/Interest/InterestService.swift
  Napzak-iOS/Napzak-iOS/Network/Report/ReportService.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/OnboardingNavigationBar.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/OnboardingTermsView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/UsernameInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/.gitkeep
  Napzak-iOS/Napzak-iOS/Presentation/Splash/View/LoginView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/ViewModel/LoginViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 호근 🍙, Feat 💻, Network 📡

#55 [Network] #46 - Register View API 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/ImagePickerManager.swift
  Napzak-iOS/Napzak-iOS/Network/Presigned/DTO/Response/PresignedProductResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Presigned/PresignedAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Presigned/PresignedService.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Request/BuyRegisterRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Request/SellRegisterRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/BuyRegisterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/SellRegisterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterProductStateSection.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/RegisterFloatingView.swift
Labels: 한열 🧄, Network 📡

#56 [Style] #37 - 장르페이지 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_home.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_home.imageset/icon_home.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_hot_tag.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_hot_tag.imageset/img_hot_tag.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_hot_tag.imageset/img_hot_tag@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_hot_tag.imageset/img_hot_tag@3x.png
  Napzak-iOS/Napzak-iOS/Presentation/Search/Model/GenreInfoModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/GenreDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Style 🖼️

#60 [Network] #59 - Onboarding API 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/UsernameInputField.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/UsernameValidation.swift
  Napzak-iOS/Napzak-iOS/Global/Models/PreferGenreModel.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseService.swift
  Napzak-iOS/Napzak-iOS/Network/Base/ErrorResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkError.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreService.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/Request/PreferGenreRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/Response/GenreDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/Response/GenreNameResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/Response/PreferGenreResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Request/NicknameRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/TermsResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreGridView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/OnboardingTermsView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/UsernameInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/GenreSelectionViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/OnboardingTermsViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/UsernameInputViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/View/LoginView.swift
Labels: 호근 🍙, Network 📡

#65 [Style] #64 - 로그아웃 UI & API 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NZAlertView.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthService.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/LogoutResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/SettingViewModel.swift
Labels: 한열 🧄, Style 🖼️

#66 [Network] #63 - 탐색, 장르 페이지 API 연동
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/ProductItemView.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeStatus.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeType.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductItemModel.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreService.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/Response/GenreDetailResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/Model/GenreInfoModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/GenreDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: 혜린 🎀, Network 📡

#74 [Fix] #73 - 이미지 경로 버그 수정
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
Labels: 한열 🧄, Fix 🔨

#72 [Network] #61 - Home API 연결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/RootView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/ProductItemView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/TabRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/NZTab.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeStatus.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeType.swift
  Napzak-iOS/Napzak-iOS/Global/Models/HomeBanner/BannerItem.swift
  Napzak-iOS/Napzak-iOS/Global/Models/HomeBanner/HomeBannersModel.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductItemModel.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Animation/ios.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/ios_splash.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/ios_splash.imageset/ios_splash.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/icon_napzak(Logo).imageset/Rectangle 10311.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/LaunchScreen.storyboard
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Home/HomeAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Home/HomeService.swift
  Napzak-iOS/Napzak-iOS/Network/Home/Response/BannerResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/BuyProductListResponseDTO .swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductItemResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductWithCountDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/SellProductListResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/GenreDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/View/LoginView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 호근 🍙, Network 📡

#70 [Network] #69 - 검색 화면 API 연동
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/SearchRecommendationResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/Model/SearchWordModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchInputViewModel.swift
Labels: 혜린 🎀, Network 📡

#68 Network/#58 profileEdit API 및 UI 수정
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Literals/StringLiterals.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/AuthService.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Request/WithDrawRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/WithDrawResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseService.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/MarketProductItemDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/MarketProductBuyListResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/MarketProductListResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Request/StoreModifyProfileRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreDetailDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreModifyProfileResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/StoreProfileDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawConfirmView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawSelectReasonView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawWriteReasonView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/WithDrawViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 어진 🧸, Feat 💻, Network 📡

#76 [Network] #71 - 상품 상세 API 연동
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/NZAlertView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/ProductCondition.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeStatus.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductItemModel.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Request/ChangeTradeStatusRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/BuyRegisterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/EditProductResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/ProductDetailResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/SellRegisterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawConfirmView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/Components/Modal/ProductOwnerOptionsModalView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/Components/ProductDetailToastView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/Model/ProductDetailModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/ViewModel/ProductDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterNavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Network 📡

#89 [Fix] #84 - 자잘한 버그 해결
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
Labels: 혜린 🎀, Fix 🔨

#91 [Hotfix] #87 - QA용 화면 연결
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/ReportModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Network/Report/DTO/Response/ReportResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/View/ReportView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: Feat 💻

#94 [Fix] #88 - QA 버그 해결
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/SearchBar.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/RegisterFloatingView.swift
Labels: 혜린 🎀, Fix 🔨

#98 [Fix] #86 - 1차 QA
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/ToastMessageView.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/AuthManager.swift
  Napzak-iOS/Napzak-iOS/Global/Literals/ColorLiteral.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Request/LoginRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Auth/DTO/Response/UserRole.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawConfirmView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawWriteReasonView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/WithDrawViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreGridView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/GenreSelectionViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/View/LoginView.swift
Labels: 호근 🍙, Fix 🔨

#97 [Feat] #96 - 뒤로가기 스와이프 활성화
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Extensions/UINavigationController+.swift
  Napzak-iOS/Napzak-iOS/Global/Extensions/View+.swift
  Napzak-iOS/Napzak-iOS/Global/Modifiers/SwipePopGestureManager.swift
Labels: 한열 🧄, Feat 💻

#100 [Fix] #90 QA 반영
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/Frame 1707483318.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/Frame 1707483318@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/Frame 1707483318@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/group5_icn.svg
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditViewModel.swift
Labels: 어진 🧸, Fix 🔨

#101 [Fix] #99 - 1차 QA (2)
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/ProductItemView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/TabRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Components/UsernameInputField.swift
  Napzak-iOS/Napzak-iOS/Global/Core/ProductLikeManager.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/UsernameValidation.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductItemModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/GenreSelectionViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/Model/ProductDetailModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/ViewModel/ProductDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/GenreDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 호근 🍙, Fix 🔨

#105 [Fix] #104 QA 2차 반영
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditViewModel.swift
Labels: 어진 🧸, Fix 🔨

#108 [Fix] #107 - 자체 QA 이슈 해결
  Napzak-iOS/Napzak-iOS/Global/Components/NZAlertView.swift
  Napzak-iOS/Napzak-iOS/Global/Modifiers/KeyboardObserver.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawConfirmView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/View/ReportView.swift
Labels: 한열 🧄, Fix 🔨

#109 [Fix] #106 - QA반영
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/RootView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/ViewModel/ProductDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/GenreDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Splash/View/SplashView.swift
Labels: 호근 🍙, Fix 🔨

#110 [Fix] #103 - QA 추가 이슈 해결
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Fix 🔨

#114 [Fix] #112 자체 QA 반영
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
Labels: 어진 🧸, Fix 🔨

#116 [Fix] #113 - QA 최종 수정사항 반영
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/WithDrawWriteReasonView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/WithDrawViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
Labels: 한열 🧄, Fix 🔨

#118 [Fix] #111 - QA 최종 수정사항 반영
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Core/ProductEventManager.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProductDetail/ViewModel/ProductDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/GenreDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Fix 🔨

#120 [Docs] #119 - README 수정
  README.md
Labels: 혜린 🎀, Docs 📑

#122 [Chore] #121 - 배너 넘어가는 시간 개선
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/Components/CarouselView.swift
Labels: 호근 🍙, Chore 🪡
