Repository napzakmarket/Napzak-iOS, pull requests merged in 2025-04, with the labels that each got.

#9 [Style] #6 - 온보딩 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/.gitkeep
  Napzak-iOS/Napzak-iOS/Global/Components/CheckRow.swift
  Napzak-iOS/Napzak-iOS/Global/Components/PrimaryButton.swift
  Napzak-iOS/Napzak-iOS/Global/Components/UsernameInputField.swift
  Napzak-iOS/Napzak-iOS/Global/Models/RowType.swift
  Napzak-iOS/Napzak-iOS/Global/Models/UsernameValidation.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_default .imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_default .imageset/Property 1=Default.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_default .imageset/Property 1=Default@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_default .imageset/Property 1=Default@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_selected .imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_selected .imageset/Property 1=Variant2.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_selected .imageset/Property 1=Variant2@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/checkbox_selected .imageset/Property 1=Variant2@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon__go.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon__go.imageset/icon__go.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon__go.imageset/icon__go@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon__go.imageset/icon__go@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_back.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_back.imageset/icon_back.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_back.imageset/icon_back@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_back.imageset/icon_back@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_next.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_next.imageset/Group 1000004790.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_next.imageset/Group 1000004790@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/icon_next.imageset/Group 1000004790@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator01.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator01.imageset/Property 1=indicator01.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator01.imageset/Property 1=indicator01@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator01.imageset/Property 1=indicator01@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator02.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator02.imageset/Property 1=indicator02.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator02.imageset/Property 1=indicator02@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator02.imageset/Property 1=indicator02@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator03.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator03.imageset/Property 1=indicator03.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator03.imageset/Property 1=indicator03@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/indicator03.imageset/Property 1=indicator03@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_default.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_default.imageset/Property 1=Default.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_default.imageset/Property 1=Default@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_default.imageset/Property 1=Default@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_disabled.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_disabled.imageset/Property 1=Variant2.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_disabled.imageset/Property 1=Variant2@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/namecheck_disabled.imageset/Property 1=Variant2@3x.png
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/.gitkeep
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/Components/OnboardingNavigationBar.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/OnboardingTermsView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/UsernameInputView.swift
Labels: 호근 🍙, Style 🖼️

#13 [Style] #8 - 등록 뷰 공통 컴포넌트 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/button_checkbox.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/button_checkbox.imageset/button_checkbox.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/button_checkbox_fill.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/button_checkbox_fill.imageset/button_checkbox_fill.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_close.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_close.imageset/icon_close.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_go_register.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_go_register.imageset/Group 1000004790 (1).svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_image__cancle.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_image__cancle.imageset/icon_image__cancle.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_photo_picker.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_photo_picker.imageset/Group 1000004800.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_warning.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_warning.imageset/Group 1000004797.svg
  Napzak-iOS/Napzak-iOS/Presentation/Register/.gitkeep
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterDescription.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterTitle.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/SellRegisterHeader.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
Labels: 한열 🧄, Style 🖼️

#15 [Style] #11 - 온보딩 장르 선택 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/ChipsContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/GenreChip.swift
  Napzak-iOS/Napzak-iOS/Global/Components/SearchBar.swift
  Napzak-iOS/Napzak-iOS/Global/Components/UsernameInputField.swift
  Napzak-iOS/Napzak-iOS/Global/Models/UsernameValidation.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_default .imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_default .imageset/Property 1=Default.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_default .imageset/Property 1=Default@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_default .imageset/Property 1=Default@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_selected .imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_selected .imageset/Property 1=Variant2.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_selected .imageset/Property 1=Variant2@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/checkbox_selected .imageset/Property 1=Variant2@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon__go.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon__go.imageset/icon__go.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon__go.imageset/icon__go@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon__go.imageset/icon__go@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_cancle_filterchip.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_cancle_filterchip.imageset/icon_cancle__filterchip.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_cancle_filterchip.imageset/icon_cancle__filterchip@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_cancle_filterchip.imageset/icon_cancle__filterchip@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_next.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_next.imageset/Group 1000004790.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_next.imageset/Group 1000004790@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_next.imageset/Group 1000004790@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_reset.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_reset.imageset/icon_reset.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_search.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_search.imageset/icon_search.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_search_cancle.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/icon_search_cancle.imageset/icon_search__cancle.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_default.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_default.imageset/Property 1=Default.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_default.imageset/Property 1=Default@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_default.imageset/Property 1=Default@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_disabled.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_disabled.imageset/Property 1=Variant2.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_disabled.imageset/Property 1=Variant2@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Global/namecheck_disabled.imageset/Property 1=Variant2@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/overlay_like.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/overlay_like.imageset/overlay_like.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/overlay_like.imageset/overlay_like@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/overlay_like.imageset/overlay_like@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/toast_warning.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Onboarding/toast_warning.imageset/Vector.svg
  Napzak-iOS/Napzak-iOS/Network/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/OnboardingMock/GenreName.swift
  Napzak-iOS/Napzak-iOS/Network/OnboardingMock/PreferGenre.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreCell.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreGridView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/OnboardingNavigationBar.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/ToastMessageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/OnboardingTermsView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/UsernameInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/GenreSelectionViewModel.swift
Labels: 호근 🍙, Style 🖼️

#16 [Style] #10 - 마이뷰 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/arrow_right.imageset/Group 1000004839.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group1_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group1_icn.imageset/group1_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group2_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group2_icn.imageset/group2_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group3_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group3_icn.imageset/group3_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group4_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group4_icn.imageset/group4_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group5_icn.imageset/group5_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group6_icn.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/group6_icn.imageset/group6_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/profile_img.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/MyPage/profile_img.imageset/Group 1000005095.svg
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/MyPageView.swift
Labels: 어진 🧸, Style 🖼️

#22 [Style] #19 - 탐색 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/Napzak_iOSApp.swift
  Napzak-iOS/Napzak-iOS/Global/Components/FilterContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NZSegmentedControl.swift
  Napzak-iOS/Napzak-iOS/Global/Components/ProductItemView.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/RowType.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/SortOption.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeStatus.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeType.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/UsernameValidation.swift
  Napzak-iOS/Napzak-iOS/Global/Literals/FontLiteral.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductFetchOption.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductItemModel.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/btn_heart_default.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/btn_heart_default.imageset/btn_heart_default.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/btn_heart_selected.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/btn_heart_selected.imageset/btn_heart_selected.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/icn_chat_count.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/icn_chat_count.imageset/icn_chat_count.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/icn_heart_count.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/icn_heart_count.imageset/icn_heart_count.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_bidding.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_bidding.imageset/img_chip_bidding.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_buy.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_buy.imageset/img_chip_buy.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_sell.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_chip_sell.imageset/img_chip_sell.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_buy_sm.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_buy_sm.imageset/img_trade_buy_sm.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_reserved_sm.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_reserved_sm.imageset/img_trade_reserved_sm.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_sell_sm.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProductItem/img_trade_sell_sm.imageset/img_trade_sell_sm.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_genre.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_genre.imageset/btn_filter_genre.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_on_sale.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_on_sale.imageset/btn_filter_on_sale.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_on_sale_selected.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_on_sale_selected.imageset/btn_filter_on_sale_selected.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_unopened.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_unopened.imageset/btn_filter_unopened.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_unopened_selected.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/btn_filter_unopened_selected.imageset/btn_filter_unopened_selected.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_arrow_down.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_arrow_down.imageset/icon_arrow_down.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_arrow_right.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_arrow_right.imageset/icon_arrow_right.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_search.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/icon_search.imageset/icon_search.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_genre_tag.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_genre_tag.imageset/img_genre_tag.svg
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Buy/BuyRegisterPrice.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/Component/GenreItemView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Style 🖼️

#23 [Style] #18 - 신고하기 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Literals/StringLiterals.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/View/ReportView.swift
Labels: 한열 🧄, Style 🖼️

#25 [Style] #24 - 장르 선택, 정렬 모달 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/FilterContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/SortModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/ViewModel/GenreSelectModalViewModel.swift
  Napzak-iOS/Napzak-iOS/Global/Components/SearchBar.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/SortOption.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductFetchOption.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_check_sort.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_check_sort.imageset/icon_check_sort.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_close_modal.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_close_modal.imageset/icon_close_modal.svg
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Style 🖼️

#31 [Style] #26 - 검색 화면 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/PlainChip.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/PlainChipContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/NavigationRouter.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_search_input.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Search/img_search_input.imageset/img_search_input.svg
  Napzak-iOS/Napzak-iOS/Presentation/Search/Component/GenreItemView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchInputViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Style 🖼️

#27 [Style] #21 마켓뷰 UI 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/profile_market.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/profile_market.imageset/profile_market.svg
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
Labels: 어진 🧸, Style 🖼️

#34 [Setting] #32 - 네트워크 기초 세팅
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/ChipsContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Chip/GenreChip.swift
  Napzak-iOS/Napzak-iOS/Global/Components/FilterContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/ViewModel/GenreSelectModalViewModel.swift
  Napzak-iOS/Napzak-iOS/Global/Models/GenreNameModel.swift
  Napzak-iOS/Napzak-iOS/Global/Models/PreferGenreModel.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ProductFetchOption.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Network/Base/BaseResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseService.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseTargetType.swift
  Napzak-iOS/Napzak-iOS/Network/Base/MoyaPlugin.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkResult.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/DTO/GenreDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/DTO/GenreNameResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/DTO/PreferGenreResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreService.swift
  Napzak-iOS/Napzak-iOS/Network/Interest/InterestAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Interest/InterestService.swift
  Napzak-iOS/Napzak-iOS/Network/OnboardingMock/GenreName.swift
  Napzak-iOS/Napzak-iOS/Network/OnboardingMock/PreferGenre.swift
  Napzak-iOS/Napzak-iOS/Network/Presigned/DTO/Response/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Presigned/PresignedAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Presigned/PresignedService.swift
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Request/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Product/ProductAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Product/ProductService.swift
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Request/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Store/DTO/Response/.gitkeep
  Napzak-iOS/Napzak-iOS/Network/Store/StoreAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Store/StoreService.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreCell.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/Components/Genre/GenreGridView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/ViewModel/GenreSelectionViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchInputView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchInputViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: 혜린 🎀, Setting ⚙️, Network 📡

#45 [Refactor] #43 - 네트워크 로직 구조 개선
  .gitignore
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/GenreSelectModalView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/ViewModel/GenreSelectModalViewModel.swift
  Napzak-iOS/Napzak-iOS/Network/Base/BaseService.swift
  Napzak-iOS/Napzak-iOS/Network/Base/MoyaPlugin.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkError.swift
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkResult.swift
  Napzak-iOS/Napzak-iOS/Network/Genre/GenreService.swift
  Napzak-iOS/Napzak-iOS/Network/Interest/InterestService.swift
Labels: 호근 🍙, Refactor 🏗️

#35 [Refactor] #30 - View, ViewModel 분리
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Buy/BuyRegisterPrice.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Buy/BuyRegisterSuggestPrice.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterDescription.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterTitle.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterDelivery.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterHeader.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterPrice.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterProductStateSection.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/Model/ReportModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/View/ReportView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Report/ViewModel/ReportViewModel.swift
Labels: 한열 🧄, Refactor 🏗️
