Repository napzakmarket/Napzak-iOS, pull requests merged in 2025-08, with the labels that each got.

#152 [Fix] #150 - 2차 스프린트 자체 QA
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/AuthManager.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_empty_search_genre_ios.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Register/icon_empty_search_genre_ios.imageset/icon_empty_search_genre_ios.svg
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Onboarding/View/GenreSelectionView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/RegisterSearchGenre.swift
Labels: 한열 🧄, Fix 🔨

#153 [Feat] #140 - Push Notification 구현
  .gitignore
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/AppDelegate.swift
  Napzak-iOS/Napzak-iOS/Application/Napzak_iOSApp.swift
  Napzak-iOS/Napzak-iOS/Application/RootView.swift
  Napzak-iOS/Napzak-iOS/Global/Components/Modal/View/PermissionAlertView.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/AuthManager.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Push/PushManager.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Push/PushPermissionManager.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/PushOffState.swift
  Napzak-iOS/Napzak-iOS/Global/Extensions/View+.swift
  Napzak-iOS/Napzak-iOS/Global/Literals/FontLiteral.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/icon_instagram.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/icon_instagram.imageset/icon_instagram.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/icon_message.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Home/icon_message.imageset/icon_message.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_notification.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_notification.imageset/Group 1000005278.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_notification.imageset/Group 1000005278@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Modal/icon_notification.imageset/Group 1000005278@3x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Info.plist
  Napzak-iOS/Napzak-iOS/Global/Style/CustomToggleStyle.swift
  Napzak-iOS/Napzak-iOS/Napzak-iOS.entitlements
  Napzak-iOS/Napzak-iOS/Network/Base/NetworkService.swift
  Napzak-iOS/Napzak-iOS/Network/Interest/InterestService.swift
  Napzak-iOS/Napzak-iOS/Network/Push/PushAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Push/PushService.swift
  Napzak-iOS/Napzak-iOS/Network/Push/Request/PushTokenRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Push/Response/PushSettingResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Home/View/HomeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 호근 🍙, Feat 💻

#155 [Network] #149 - 채팅 API 연결 및 채팅 로직 구현
  Napzak-iOS/Napzak-iOS.xcodeproj/project.pbxproj
  Napzak-iOS/Napzak-iOS/Application/Napzak_iOSApp.swift
  Napzak-iOS/Napzak-iOS/Global/Core/Auth/AuthManager.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/ChatType.swift
  Napzak-iOS/Napzak-iOS/Global/Enums/TradeType.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ChatMetaData.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatService.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Request/ChatInfoRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Request/ChatMessageRequestDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatDetailResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatMessageResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatRoomEnterResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatRoomIdListResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatRoomResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/StoreIdResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Components/ChatBody.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Components/ChatStarter.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Manager/ChatEventManager.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Manager/ChatStompManager.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatDetailModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatMessageModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatRoomModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/ViewModel/ChatDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/ViewModel/ChatViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/TabBar/View/NZTabBarView.swift
Labels: 혜린 🎀, Feat 💻, Network 📡

#161 Fix/#160 2차 QA 반영
  Napzak-iOS/Napzak-iOS/Global/Components/FilterContainerView.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_getting.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_getting.imageset/getting_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_getting_purple.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_getting_purple.imageset/getting_purple_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_onsale.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_onsale.imageset/onsale_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_onsale_purple.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Market/btn_onsale_purple.imageset/onsale_purple_icn.svg
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProfileEdit/btn_imagedit.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/ProfileEdit/btn_imagedit.imageset/imagedit_icn.svg
  Napzak-iOS/Napzak-iOS/Network/Product/DTO/Response/LikedProductsResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/LikeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
Labels: 어진 🧸, Fix 🔨

#163 [Fix] #162 - 기디 2차 QA 반영
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/SettingView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/Components/Sell/SellRegisterDelivery.swift
  Napzak-iOS/Napzak-iOS/Presentation/Register/ViewModel/RegisterViewModel.swift
Labels: 한열 🧄, Fix 🔨

#172 [Fix] #171 2차 QA 반영
  Napzak-iOS/Napzak-iOS/Presentation/Market/MarketView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/LikeView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/View/MyPageView.swift
  Napzak-iOS/Napzak-iOS/Presentation/ProfileEdit/ProfileEditView.swift
Labels: 어진 🧸, Fix 🔨

#174 [Fix] #168 - 2차 스프린트 추가 QA 반영 및 버그 개선
  Napzak-iOS/Napzak-iOS/Global/Core/Push/PushManager.swift
  Napzak-iOS/Napzak-iOS/Global/Models/ChatMetaData.swift
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/btn_send.imageset/Contents.json
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/btn_send.imageset/btn_send_image.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/btn_send.imageset/btn_send_image@2x.png
  Napzak-iOS/Napzak-iOS/Global/Resources/Assets.xcassets/Chat/btn_send.imageset/btn_send_image@3x.png
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatAPI.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/ChatService.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatDetailResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Network/Chat/DTO/Response/ChatMessageResponseDTO.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Components/ChatStarter.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Manager/ChatStompManager.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/Model/ChatDetailModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ChatView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/View/ImageDetailView.swift
  Napzak-iOS/Napzak-iOS/Presentation/Chat/ViewModel/ChatDetailViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/SettingViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Mypage/ViewModel/WithDrawViewModel.swift
  Napzak-iOS/Napzak-iOS/Presentation/Search/View/SearchView.swift
Labels: 혜린 🎀, Fix 🔨
